# Generated by Django 4.0.5 on 2022-06-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBCTestResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CBCTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('labNumber', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=50)),
                ('dateRequested', models.DateTimeField()),
                ('dateReceived', models.DateTimeField()),
                ('whiteBloodCells', models.FloatField()),
                ('redBloodCells', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('meanCorpuscularVolume', models.FloatField()),
                ('meanCorpuscularHb', models.FloatField()),
                ('meanCorpuscularHbConc', models.FloatField()),
                ('rbcDistributionWidth', models.FloatField()),
                ('plateletCount', models.FloatField()),
                ('segmenters', models.FloatField()),
                ('lymphocytes', models.FloatField()),
                ('monocytes', models.FloatField()),
                ('eosinophils', models.FloatField()),
                ('basophils', models.FloatField()),
                ('bands', models.FloatField()),
                ('absoluteSeg', models.FloatField()),
                ('absoluteLymphocyteCount', models.FloatField()),
                ('absoluteMonocyteCount', models.FloatField()),
                ('absoluteEosinophilCount', models.FloatField()),
                ('absoluteBasophilCount', models.FloatField()),
                ('absoluteBandCount', models.FloatField()),
                ('testImage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isabuhaywebapp.cbctestresultimage')),
            ],
        ),
    ]
