# Generated by Django 4.0.5 on 2022-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCTestResultPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testImage', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
