# Generated by Django 4.0.5 on 2022-06-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0002_cbctestresultpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbctestresultpdf',
            old_name='testImage',
            new_name='testPDF',
        ),
    ]
