# Generated by Django 4.0.5 on 2022-06-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0003_rename_testimage_cbctestresultpdf_testpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbctestresult',
            name='testPDF',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isabuhaywebapp.cbctestresultpdf'),
        ),
        migrations.AlterField(
            model_name='cbctestresult',
            name='testImage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isabuhaywebapp.cbctestresultimage'),
        ),
    ]
