# Generated by Django 4.0.5 on 2022-06-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0004_cbctestresult_testpdf_alter_cbctestresult_testimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCTestResultDocx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testDocx', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.AddField(
            model_name='cbctestresult',
            name='testDocx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isabuhaywebapp.cbctestresultdocx'),
        ),
    ]
