# Generated by Django 4.0.5 on 2022-11-11 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0009_alter_user_uploads_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
